#include <cassert>
#include <cstdio>
#include <cstring>
#include "../src/mac/MacFiles.h"
int main() {
    MacFiles c;c.reset();assert(c.count()==1 && c.entry(2)->parent==1);
    c.application=c.add(2,"Game","PROGDIR:",true);
    c.data=c.add(c.application,"Alone Data","data",true);
    c.system=c.add(2,"System Folder","",true);
    assert(c.initializeDirectories()==0);
    auto file=c.add(c.data,"ITD_RESS.PAK","data/ITD_RESS.PAK",false,123456,765);
    uint32_t id=999;
    assert(c.resolve(0,0,":Alone Data:itd_ress.pak",id)==0 && id==(uint32_t)file);
    assert(c.resolve(0,0,"Alone:Game:Alone Data:",id)==0 && id==c.data);
    assert(c.resolve(0,c.data,"::",id)==0 && id==c.application);
    assert(c.resolve(0,2,"::",id)==c.dirNFErr);
    assert(c.resolve(0,c.data,":ITD_RESS.PAK:",id)==c.dirNFErr);
    assert(c.resolve(0,0,":Alone Movies:",id)==c.fnfErr);
    assert(c.resolve(0,0,":Unexpected:",id)==c.unsupported);
    assert(c.resolve(0,c.data,"MISSING.PAK",id)==c.fnfErr);
    assert(c.resolve(0,c.data,"\xff",id)==c.unsupported);
    assert(c.resolve(0,0,"\xff:Game:",id)==c.unsupported);
    assert(c.resolve(22,0,"",id)==c.nsvErr);
    assert(c.resolve(0,file,"",id)==c.dirNFErr);
    assert(c.resolve(-1,0,"",id)==0 && id==2);
    bool created=false;
    auto wd=c.openWD(c.data,0x41495444,&created);assert(created);
    assert(c.directoryFor(wd,id)==0 && id==c.data);
    assert(c.wdProcess(wd)==0x41495444);
    assert(c.resolve(wd,0,"itd_ress.pak",id)==0 && id==(uint32_t)file);
    assert(c.openWD(c.data,0x41495444,&created)==wd && !created);
    assert(c.openWD(c.data,0x41495445)==wd && c.wdProcess(wd)==0x41495444);
    int16_t queried=c.systemWD;uint32_t process=0,directory=0;
    assert(c.queryWD(queried,0,process,directory)==0 && directory==c.system && process==0x4552494b);
    assert(c.closeWD(c.systemWD)==0);
    assert(c.queryWD(queried,0,process,directory)==c.nsvErr);
    assert(c.closeWD(c.systemWD)==c.rfNumErr);
    queried=0;process=0x41495444;
    assert(c.queryWD(queried,1,process,directory)==0 && queried==wd && directory==c.data);
    queried=0;process=0x41495445;
    assert(c.queryWD(queried,1,process,directory)==c.nsvErr && queried==0 && process==0x41495445);
    queried=0;process=0;
    assert(c.queryWD(queried,1,process,directory)==0 && queried==c.applicationWD && directory==c.application);
    assert(c.closeWD(c.applicationWD)==0 && c.directoryFor(c.applicationWD,id)==0);
    assert(c.openWD(c.application,123,&created)==c.applicationWD && !created);
    queried=0;process=0;
    assert(c.queryWD(queried,2,process,directory)==0 && queried==wd);
    queried=0;process=0;
    assert(c.queryWD(queried,32767,process,directory)==c.nsvErr);
    queried=0;
    assert(c.queryWD(queried,-1,process,directory)==0 && queried==c.volumeRef && directory==2);
    assert(c.closeWD(c.volumeRef)==0 && c.closeWD(0)==c.rfNumErr);
    assert(c.setDefault(wd)==0 && c.defaultRef()==wd);
    assert(c.resolve(0,0,"itd_ress.pak",id)==0 && id==(uint32_t)file);
    assert(c.setDefault(42)==c.nsvErr && c.defaultRef()==wd);
    assert(c.setDefault(0)==0 && c.defaultRef()==wd);
    assert(c.setDefault(wd,"Alone")==0 && c.defaultRef()==wd);
    assert(c.setDefault(c.volumeRef,"Unknown")==c.unsupported && c.defaultRef()==wd);
    assert(c.setHierarchicalDefault(c.volumeRef,c.data)==0 && c.defaultRef()==c.volumeRef);
    assert(c.directoryFor(0,id)==0 && id==c.data);
    assert(c.resolve(0,0,"itd_ress.pak",id)==0 && id==(uint32_t)file);
    assert(c.setHierarchicalDefault(wd,0)==0 && c.defaultRef()==c.volumeRef);
    assert(c.setHierarchicalDefault(wd,9999)==c.fnfErr);
    assert(c.directoryFor(0,id)==0 && id==c.data);
    assert(c.setHierarchicalDefault(42,0)==c.nsvErr);
    assert(c.setHierarchicalDefault(c.volumeRef,file)==c.fnfErr);
    assert(c.setHierarchicalDefault(wd,0,"ITD_RESS.PAK")==c.fnfErr);
    assert(c.setHierarchicalDefault(42,9999,"Alone:Game:Alone Data:")==0);
    assert(c.setHierarchicalDefault(0,0,"::")==0 && c.directoryFor(0,id)==0 && id==c.application);
    assert(c.setHierarchicalDefault(0,0,":Alone Data:")==0 && c.directoryFor(0,id)==0 && id==c.data);
    assert(c.setDefault(wd)==0 && c.defaultRef()==wd);
    assert(c.setDefault(c.volumeRef)==0 && c.directoryFor(0,id)==0 && id==2);
    assert(c.closeWD(wd)==0 && c.directoryFor(wd,id)==c.nsvErr);
    assert(c.closeWD(wd)==c.rfNumErr);
    assert(c.openWD(file,0)==c.fnfErr);
    assert(c.openWD(2,0)==c.volumeRef);
    auto r=c.open(file,true,true), d=c.open(file,false,false);
    assert(r>0 && d>0 && r!=d && c.fork(0)==nullptr);
    assert(c.fork(r)->resource && c.fork(r)->writable && c.fork(r)->position==0);
    assert(c.entry(c.fork(r)->id)->resourceSize==765);
    assert(!c.fork(d)->resource && !c.fork(d)->writable);
    assert(c.entry(c.fork(d)->id)->dataSize==123456);
    assert(c.seek(d,1,65530)==0 && c.fork(d)->position==65530);
    assert(c.seek(d,3,-30)==0 && c.fork(d)->position==65500);
    assert(c.seek(d,2,-7)==0 && c.fork(d)->position==123449);
    assert(c.seek(d,1,-1)==-40 && c.fork(d)->position==123449);
    assert(c.seek(d,3,0x7fffffff)==-39 && c.fork(d)->position==123456);
    assert(c.seek(d,1,(int32_t)0x80000000)==-40 && c.fork(d)->position==123456);
    assert(c.seek(d,9,0)==c.unsupported);
    assert(c.seek(0,1,0)==c.rfNumErr);
    const MacFiles::Fork* found=nullptr;
    assert(c.queryFork(0,1,999,found)==0 && found==c.fork(r));
    assert(c.queryFork(-1,2,999,found)==0 && found==c.fork(d));
    assert(c.queryFork(1,2,999,found)==0 && found==c.fork(d));
    auto queryWD=c.openWD(c.data,0);
    assert(c.queryFork(queryWD,2,999,found)==0 && found==c.fork(d));
    assert(c.queryFork(0,3,0,found)==-38 && !found);
    assert(c.queryFork(0,32767,0,found)==-38 && !found);
    assert(c.queryFork(0x1234,1,0,found)==c.nsvErr && !found);
    assert(c.queryFork(0x1234,0,d,found)==0 && found==c.fork(d));
    assert(c.queryFork(0x1234,0,0,found)==c.rfNumErr && !found);
    assert(c.queryFork(0,-1,0,found)==c.unsupported && !found);
    assert(c.close(r)==0 && !c.fork(r) && c.close(r)==c.rfNumErr);
    assert(c.queryFork(0,1,0,found)==0 && found==c.fork(d));
    assert(c.queryFork(0,2,0,found)==-38 && !found);
    assert(c.open(c.data,false,false)==c.fnfErr);
    for(int i=1;i<c.maxOpen;++i)assert(c.open(file,false,false)>0);
    assert(c.open(file,false,false)==-42);
    auto n=c.count();
    assert(c.add(c.data,"itd_ress.pak","",false)==c.paramErr);
    assert(c.add(c.data,"bad:name","",false)==c.paramErr);
    assert(c.add(file,"child","",false)==c.paramErr);
    assert(c.add(c.data,"abcdefghijklmnopqrstuvwxyz123456","",false)==c.unsupported);
    char path[161];memset(path,'x',160);path[160]=0;
    assert(c.add(c.data,"too-long-path",path,false)==c.unsupported);
    assert(c.count()==n);
    for(int i=n;i<c.maxEntries;++i) { char name[32];snprintf(name,sizeof(name),"entry%d",i);assert(c.add(c.data,name,"",false)>0); }
    assert(c.add(c.data,"overflow","",false)==c.unsupported && c.count()==c.maxEntries);
    c.reset();c.application=c.add(2,"Game","",true);
    for(int i=0;i<c.maxWD;++i) {
        char name[32];snprintf(name,sizeof(name),"dir%d",i);
        auto dir=c.add(c.application,name,"",true);auto w=c.openWD(dir,i);assert(c.directoryFor(w,id)==0);
    }
    auto extra=c.add(c.application,"extra","",true);
    assert(c.openWD(extra,99)==-121);
    c.reset();assert(c.count()==1 && c.fork(d)==nullptr && c.directoryFor(wd,id)==c.nsvErr);
    puts("PASS mac-files: paths, fork identity, working directories, errors, atomic capacity limits");
}
