#!/usr/bin/env python3
"""Generate the compiled raw glyph table from the original Mac bitmap capture."""
import argparse
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUTPUT=ROOT/'src/mac/Times14Bitmap.h'
SOURCE=ROOT/'resources/times14-bitmap.json'
def build():
    glyphs=json.loads(SOURCE.read_text())['glyphs']
    if len(glyphs)!=224:raise ValueError('expected MacRoman 32..255')
    records=[];bits=[]
    for left,top,width,rows in glyphs:
        if not (-8<=left<=8 and -20<=top<=12 and 0<=width<=16 and len(rows)<=32
                and all(type(row)==int and 0<=row<1<<width for row in rows)):
            raise ValueError('invalid glyph geometry')
        records.append('{%d,%d,%d,%d,%d}'%(left,top,width,len(rows),len(bits)))
        bits.extend(rows)
    return ("// Generated by tools/times14_bitmap.py; original Times/plain/14 bitmap capture.\n"
            "#ifndef AITD_TIMES14_BITMAP_H\n#define AITD_TIMES14_BITMAP_H\n"
            "namespace Times14Bitmap {\n"
            "struct Glyph { int8_t left,top; uint8_t width,height; uint16_t offset; };\n"
            "static const Glyph glyphs[224]={\n"+',\n'.join(records)+"\n};\n"
            "static const uint16_t rows[]={\n"+','.join(str(row)for row in bits)+"\n};\n"
            "}\n#endif\n")
def capture(folder):
    glyphs=[]
    for character in range(32,256):
        data=(folder/f'glyph-{character:03d}.bin').read_bytes()
        if len(data)!=1024 or not set(data)<={0,26}:raise ValueError('invalid original glyph capture')
        points=[(i%32,i//32) for i,value in enumerate(data) if value]
        if points:
            left=min(x for x,y in points);right=max(x for x,y in points)+1
            top=min(y for x,y in points);bottom=max(y for x,y in points)+1
            if not (0<left<right<32 and 0<top<bottom<32):raise ValueError('cropped glyph')
            rows=[sum(1<<(right-left-1-x)for x in range(right-left)if data[y*32+left+x])for y in range(top,bottom)]
            glyphs.append([left-8,top-20,right-left,rows])
        else:glyphs.append([0,0,0,[]])
    SOURCE.write_text(json.dumps({'description':'Times/plain/14 monochrome glyphs captured from original Macintosh QuickDraw; MacRoman 32..255. Advances are in Times14Metrics.h.','glyphs':glyphs},indent=2)+'\n')
if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true');parser.add_argument('--capture-dir',type=Path)
    args=parser.parse_args()
    if args.capture_dir:capture(args.capture_dir)
    output=build()
    if args.check:
        if OUTPUT.read_text()!=output:raise SystemExit('font table differs from capture')
        print('PASS Times14 bitmap: 224 bounded original glyphs, generated table matches')
    else:OUTPUT.write_text(output)
