#!/usr/bin/env python3
"""Generate packed original Times/plain/36 glyphs and measured advances."""
import argparse
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
SOURCE=ROOT/'resources/times36-bitmap.json'
OUTPUT=ROOT/'src/mac/Times36Bitmap.h'

def build():
    source=json.loads(SOURCE.read_text());glyphs=source['glyphs']
    if len(glyphs)!=224 or source['fontInfo']!=[30,9,39,0]:raise ValueError('Times36 capture extent/metrics')
    records=[];bits=[]
    for left,top,width,advance,rows in glyphs:
        if not (-16<=left<=16 and -40<=top<=16 and 0<=width<=48 and 0<=advance<=48 and len(rows)<=48
                and all(type(row)==int and 0<=row<1<<width for row in rows)):raise ValueError('glyph bounds')
        stride=(width+7)//8
        records.append('{%d,%d,%d,%d,%d,%d}'%(left,top,width,len(rows),advance,len(bits)))
        for row in rows:
            bits.extend((row<<(stride*8-width)).to_bytes(stride,'big'))
    if len(bits)>65535:raise ValueError('glyph offset overflow')
    return ('// Generated by tools/times36_bitmap.py; original Times/plain/36 artwork.\n'
            '#ifndef AITD_TIMES36_BITMAP_H\n#define AITD_TIMES36_BITMAP_H\n'
            'namespace Times36Bitmap {\n'
            'struct Glyph { int8_t left,top; uint8_t width,height,advance; uint16_t offset; };\n'
            'static const Glyph glyphs[224]={\n'+',\n'.join(records)+'\n};\n'
            'static const uint8_t bits[]={\n'+','.join(map(str,bits))+'\n};\n}\n#endif\n')

def capture(folder):
    metrics={int(c):(int(x)-100,int(f)) for c,x,f in (line.split() for line in (folder/'times36-metrics.txt').read_text().splitlines())}
    if set(metrics)!=set(range(32,256)) or any(f!=32768 for _,f in metrics.values()):raise ValueError('advance capture')
    if (folder/'fontinfo.txt').read_text()!='TIMES36 FontInfo 30,9,39,0\n':raise ValueError('FontInfo capture')
    glyphs=[]
    for c in range(32,256):
        data=(folder/f'glyph-{c:03d}.bin').read_bytes()
        if len(data)!=9216 or not set(data)<={0,255}:raise ValueError('glyph pixels')
        points=[(i%96,i//96) for i,v in enumerate(data) if v==0]
        if points:
            l=min(x for x,y in points);r=max(x for x,y in points)+1;t=min(y for x,y in points);b=max(y for x,y in points)+1
            if not (0<l<r<96 and 0<t<b<96):raise ValueError('cropped glyph')
            rows=[sum(1<<(r-l-1-x) for x in range(r-l) if data[y*96+l+x]==0) for y in range(t,b)]
            glyphs.append([l-48,t-48,r-l,metrics[c][0],rows])
        else:glyphs.append([0,0,0,metrics[c][0],[]])
    SOURCE.write_text(json.dumps({'description':'Original Macintosh Times/plain/36 monochrome glyphs and measured integer advances; MacRoman 32..255.','fontInfo':[30,9,39,0],'glyphs':glyphs},indent=2)+'\n')

if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--capture-dir',type=Path);p.add_argument('--check',action='store_true');a=p.parse_args()
    if a.capture_dir:capture(a.capture_dir)
    generated=build()
    if a.check:
        if OUTPUT.read_text()!=generated:raise SystemExit('font table differs from capture')
        print('PASS Times36: 224 bounded original glyphs, generated table matches')
    else:OUTPUT.write_text(generated)
